# space
{{- if .Values.env.enabled }}
{{- range .Values.envFrom }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.fullnameOverride }}
spec:
    secretStoreRef:
      name: awssecretsmanager
      kind: ClusterSecretStore
    refreshInterval: 1m
    target:
      name: {{ .secretRef.name }}
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: {{ .secretRef.name }}
{{- end }}
{{- end }}

---

{{- $JavaOpts := default .Values.JavaOpts ( default dict ) }}
{{- if $JavaOpts.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: java-opts
spec:
    secretStoreRef:
      name: awssecretsmanager
      kind: ClusterSecretStore
    refreshInterval: 1m
    target:
      name: java-opts
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: java-opts
{{- else if or $JavaOpts.disabled (not (hasKey $JavaOpts "disabled")) }}
{{- end }}