apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  # annotations:
  #   notifications.argoproj.io/subscribe.on-sync-succeeded.slack: a_internal_devops
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers: []
spec:
  # Project description
  description: This project will hold all prod applications

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'